### ISSUE TITLE
PERT： 公式（5）R^L 的 L 是 最大长度N吗？

### ISSUE THREAD

**Issue by xsthunder** [ymcui/PERT#11]
Cui老师您好！

看到的论文您的 [\[2203.06906\] PERT: Pre-training BERT with Permuted Language Model](https://arxiv.org/abs/2203.06906)，对我很有帮助，并正在复现它。过程中，有一个细节不明白，希望您能不吝指点。

对于公式（5），L是最大长度N吗？如下图。前面您提到L是transfomer的层数，不能理解为什么层数L和p_i有关。

![图片](https://user-images.githubusercontent.com/15523788/205199494-a3e9b483-ba81-461b-a325-6bfd43b1aff3.png)

H^{~}_{i}的维度是(1,768)， H^{T}维度是 (768，N)， 那么 b 的维度应该是(N)。

希望能尽快得到您的回复，谢谢。

**Comment by ymcui** [comment]
你好，这里是笔误，应该是序列最大长度N。

**Comment by xsthunder** [comment]
谢谢您
