### ISSUE TITLE
The shape of Equation

### ISSUE THREAD

**Issue by kehanlu** [ymcui/PERT#3]
Hi, 
Is the shape of p_i, b in equation 5 should be in R^{k} not R^{L}?

In the paper https://arxiv.org/pdf/2203.06906.pdf

**Comment by kehanlu** [comment]
To my understanding, is the objective to maximize the dot product between `H_欢` and `H^m_喜`)?

for example:
H = [我, 欢, 喜, 吃, 果, 苹] // permuted order
\tilde{H}^m = [喜, 欢 苹, 果, 是] // chosen token
y_i = [x, 0, 1, x, 2, 3]

![image](https://user-images.githubusercontent.com/22369406/159711061-470ff4f1-5aab-48c8-93ef-82708d9a7f9a.png)

**Comment by ymcui** [comment]
Hi, thank you for your question.

### 1. Is the shape of p_i, b in equation 5 should be in R^{k} not R^{L}?
Actually, we have tried both, and their performances are similar.
When predicting in the space of $L$, a simple input mask can be applied to mask those are not candidate outputs.

### 2. training objective
The input for transformer is already permuted. Let's still take the example in this picture.
```
Input = [我，**欢**，**喜**，吃，**果**，**苹**]
H = [H_我，H_欢，H_喜，H_吃，H_果，H_苹]
```
\tilde{H}^m should be a subset that is chosen for prediction (marked in boldface). H' stands for representation after FFN+Dropout+LN.
```
\tilde{H}^m = [H'_欢，H'_喜，H'_果，H'_苹]
```
Finally, a dot product is calculated by the followings.
```
[H'_欢，H'_喜，H'_果，H'_苹] × [H_我，H_欢，H_喜，H_吃，H_果，H_苹]
```
where,
```
H'_欢 predicts the position 2, i.e., the index (in the input sequence) of '喜' 
H'_喜 predicts the position 1, i.e., the index (in the input sequence) of '欢' 
...
```

**Comment by kehanlu** [comment]
1. Isn't the $L$ represents the number of transformer layers? How does the candidate representations form with length L?

2. thank you for your explanation.

**Comment by ymcui** [comment]
Sorry, I mean $N$, i.e., the length of the input.

**Comment by kehanlu** [comment]
Thank you. That makes sense.
