### ISSUE TITLE
关于chinese-pert-base-mrc

### ISSUE THREAD

**Issue by qiuxia-alone** [ymcui/PERT#8]
你好，当我用hfl/chinese-pert-base-mrc或large进行阅读理解时，尚未进行微调，文本为“我叫沃尔夫冈，我住在柏林。”，问题为“我弟弟住在哪里”，此时得到的答案为“柏林”。
        当我把问题改为“我在哪里工作”、“我弟弟住在哪里”、“我来自哪里”、“我妹妹来自哪里”等，得到答案也是柏林，概率也都是0.9多，请问这种情况该如何改善呢？

**Comment by ymcui** [comment]
这个是抽取型阅读理解，**答案是从context里抽取的。**
你列举这些问题大多数都属于不可回答的问题。
在线demo仅供演示，具体应用还需要自己在相应数据上适配。

**Comment by qiuxia-alone** [comment]
> 这个是抽取型阅读理解，**答案是从context里抽取的。** 你列举这些问题大多数都属于不可回答的问题。 在线demo仅供演示，具体应用还需要自己在相应数据上适配。

如果针对不可回答的问题，希望得到空或概率比较低的答案，是需要构造一些空答案的训练数据么？

**Comment by ymcui** [comment]
是，具体参照SQuAD 2.0数据集。
